### ISSUE TITLE
Getting Tokens for relevant chain

### ISSUE THREAD

**Issue by alirizvi512** [Glitter-Finance/Glitter-SDK-Core#24]
I cant see any method to get token list for relevant chain. It would be great if you expose that method.

**Comment by saadjhk** [comment]
@alirizvi512 for evm you have the `getAddress` method available, you can call it like
`sdk.ethereum.getAddress("tokens", "USDC");`

**Comment by andropixels** [comment]
getBridgeTokenList method is added  and will get merged in next release !
